# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f40ee42519f3c295c3c8ee8f3cfec7a79d7ef172b989ef8c1bb728d84d2257c7c7614f7e09a99e2dd7f537c5df09777a6aa4b32237ec587aea56da5392890bae

test:
  secret_key_base: bdad1c692f3f65a1f0d12a117e486fdd59864e86f494b2cdcf4602982d02d542acb3bdaf77577c822675745970cfa90a934e35eb852c0866366776e69dc722ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
